stages:
  - build
  - release

asset-job:
  stage: build
  image: 
    name: lentilus/xettelkasten:bash
    pull_policy: always
  script:
    - cp -r . /root/zettelkasten
    - xettelkasten ls
    - generate_assets &> logs.txt || [[ -f /xettelkasten/assets/glossary/glossary.pdf ]] || failed=1
    - cat /xettelkasten/assets/glossary/glossary.log >> logs.txt
    # - if [[ $failed -eq 1 ]]; then; cat logs.txt; exit; fi
    - echo "pdf successfully created!"
    - cp /xettelkasten/assets/glossary/glossary.pdf .
    - echo JOB_ID=$CI_JOB_ID >> JOB_ID.env
  artifacts:
    paths:
      - glossary.pdf
      - logs.txt
    reports:
      dotenv: JOB_ID.env

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: asset-job
      artifacts: true
  script:
    - echo "releasing..."
  release:
    name: 'Release Executables $CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: 'glossary.pdf'
          url: '${CI_PROJECT_URL}/-/jobs/${JOB_ID}/artifacts/file/glossary.pdf'
          filepath: '/export/glossary.pdf'
        - name: 'logs.txt'
          url: '${CI_PROJECT_URL}/-/jobs/${JOB_ID}/artifacts/file/logs.txt'
          filepath: '/export/logs.txt'
  only:
    - master
